### Cadastrar um nova categoria
POST https://localhost:5001/api/categoria/create
Content-Type: application/json

{
    "Nome" : "Bebida"
}

### Listar todas as categorias
GET https://localhost:5001/api/categoria/list